char *create_array(unsigned int size, char c);
char *_strdup(char *str);
int _strlen(char *s);
char *_memcpy(char *dest, char *src, unsigned int n);
char *str_concat(char *s1, char *s2);
int **alloc_grid(int width, int height);
void free_grid(int **grid, int height);
char *_strcpy(char *dest, char *src);
char *argstostr(int ac, char **av);
char *_strncpy(char *dest, char *src, int n);
int count_words(char *str);
